on:
  push:
    branches: [main, develop, 'feature/*', 'release/*', 'hotfix/*']
  repository_dispatch:

jobs:
  ping-pong:
    runs-on: [self-hosted, linux]
    steps:
      - name: PING - Dispatch initiating repository event
        if: github.event.action != 'pong'
        run: |
          curl -X POST https://atc-github.azure.cloud.bmw/Service-and-Repairs/cars-conwoy-curl-jq/.github/workflows/test-workflow.yml/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - name: ACK - Acknowledge pong from remote repository
        if: github.event.action == 'pong'
        run: |
          echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
          curl -X POST https://atc-github.azure.cloud.bmw/Service-and-Repairs/cars-conwoy-curl-jq/.github/workflows/test-workflow.yml/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          --data '{"event_type": "ack", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
